### PR TITLE
Replacing LongTimeString and LongTimeDate, Removing ICloneable

### PR DESCRIPTION
**Pull request by guillaumejay**

### CODE REVIEW

**Comment by guillaumejay** [comment]
Issue #237

**Comment by guillaumejay** [comment]
I pulled two issues in the same request, is it okay ?

**Comment by mcavigelli** [comment]
Salut Guillaume

Thank you for your two fixes!
I put a small simplification on top of it, I hope that is okay for you.

The Clone() method is not used on the interface and the return value can be of type IRecordInfo.
That removes the necessity of a cast.

Yes, in general one pull request per issue would be desirable.
But in this case, the issues were very small.

Merci pour ton aide avec FileHelpers, Matthias

**Comment by guillaumejay** [comment]
My gitfu is still weak, so when I commited my second issue, it was automatically added in the first pull request. Still have things to learn.

Simplify as you want :)

**Pull request merged**
