### PR TITLE
Make FieldLength/FieldOrder public and writable

### PR DESCRIPTION
**Pull request by merkt**
There is currently no way to set the field lengths for a FixedLengthRecord that I can find so I would like to make the FieldLength property in FixedLengthField public and settable.

### CODE REVIEW

**Comment by MarcosMeli** [comment]
You can add some tests for this change, I think that something can fail if you change the field lenght at runtime

For example the library can cache the total length to avoid constant calculation, and now it must recalculate the record length upon each change

Thanks

**Comment by merkt** [comment]
I've added a test for this, as requested.

**Comment by merkt** [comment]
Added ability to change field order at runtime with tests.

**Comment by merkt** [comment]
@MarcosMeli Any chance I could get this request merged?

**Pull request closed without merging**
