### PR TITLE
Minor formatting changes.

### PR DESCRIPTION
**Pull request by s-moon**
Small punctuation changes.

### CODE REVIEW

**Comment by s-moon** [comment]
I'm wondering if I should have made some of those full-stops, colons, as you did in the first example? This applies to the other pull-request, too.

Not sure :-( Both seem valid, but I didn't notice that you had already started with the colon in the first one.

Are you able to selectively merge? Leave out the full stops for the parts where it refers to examples, but keep any other changes? I can go back and use colons consistently later.

**Comment by s-moon** [comment]
I found a way to fix my broken fixes! Now uses colons so should be fine to merge in once you check it over. Sorry for the multi-commits!

**Comment by MarcosMeli** [comment]
Hi s-moon I'm merging when I get some time, just cheking a bit before merge but nothing wrong with the edits, Thanks !!

You can also create a unifified Pull Request for changes in various files if you want, if not, is fine too 

Thanks for your contributions !!

**Comment by s-moon** [comment]
That would be easier for you (one pull) but that facility on your website to edit pages is brilliant (and simple for me) though seems to do only one page at a time. Is that right? Can I edit multiple and just do one pull request?

**Comment by MarcosMeli** [comment]
You are right, you can only edit one file that way, and is the best one, so is all fine with multiple PRs :+1: 

Thanks for your help

**Pull request merged**
