### PR TITLE
Remove NuGet.targets from .nuget

### PR DESCRIPTION
**Pull request by akoeplinger**
It is not required anymore since newer NuGet versions recommend Automatic Package Restore instead of using the .targets file.

This should make Travis CI green.

### CODE REVIEW

**Comment by MarcosMeli** [comment]
Perfect, merged !!

**Comment by MarcosMeli** [comment]
It succeed, with the changes in #59 and #107 the lib is working great on Mono

@akoeplinger : about NuGet deploy, I must use portable libraries or MonoDevelop direct consume the 4.0 version or 4.5 of the assembly

Thanks again !!

**Comment by akoeplinger** [comment]
Sorry, I don't understand what you're asking about NuGet deploy, but a recent MonoDevelop works fine here.

**Comment by MarcosMeli** [comment]
I was asking if Mono can consume NuGet packages targeting .net 4.0 or 4.5 or is better to use a special folder inside NuGet with the binaries compiled with mono itself. 
But I realized that works with the first scenario
Sorry

**Comment by akoeplinger** [comment]
Yes, it can consume both 4.0 and 4.5 DLLs :)

**Pull request merged**
