### PR TITLE
Secured DateTime pattern parsing by making them culture-invariant.

### PR DESCRIPTION
**Pull request by eugeneavry**
Closes bug #123

### CODE REVIEW

**Comment by MarcosMeli** [comment]
Great @eugeneavry  !!

Can you provide a simple Test Case that makes the library fails with the current implementation, so we can ensure no regressions in the future

I tought than using a explicit format and with null it will use Invariant

Thanks !!

**Comment by eugeneavry** [comment]
@MarcosMeli, you are welcome, sir!

This is a very subtle pitfall!

> I tought than using a explicit format and with null it will use Invariant

No surprise here - my initial guess was the same, alas, it appeared to be an easy way to shoot yourself in a foot.

There's a wonderful [question](http://stackoverflow.com/questions/18961520/why-datetime-parseexactstring-string-iformatprovider-need-the-iformatprovide) on the StackOverflow that gives it a comprehensive explanation. You should definitely take a look at it! (no doubt, @jskeet knows about the i18n :smile: )

> Can you provide a simple Test Case that makes the library fails with the current implementation, so we can ensure no regressions in the future

Sure thing, just give me some time.

**Comment by MarcosMeli** [comment]
@eugeneavry I got it now, in fact in other apps I use it parse month names, etc.

So avoid breaking changes we need to provide a way to pass a Culture in the converter

For example, if you want to parse "11 de Agosto de 1990" You need to provide the Spanish culture to the converter or it will be impossible with InvariantCulture

No problem about the time, I will targetting this change for 3.2

**Comment by MarcosMeli** [comment]
Here is the method that defaults to the CurrentInfo if no provider is used

http://referencesource.microsoft.com/#mscorlib/system/globalization/datetimeformatinfo.cs,ddc392c731e1f52f

**Comment by MarcosMeli** [comment]
Just created a new branch

https://github.com/MarcosMeli/FileHelpers/tree/culture-awere-dateconverter

To allow users to pass a culture in the converter, for example:

    [DelimitedRecord(",")]
    private class OnlyOneDateFormatEnglish1
    {
        [FieldConverter(ConverterKind.Date, "dd/MMMM/yy", "en")]
        public DateTime Fecha;
    }

Instead of using null now uses the Culture provided, also the ToString methods uses the culture

https://github.com/MarcosMeli/FileHelpers/commit/99c1aec8ee3085ee04c442862bbc3c91c5fe8507#diff-07405c1417977c1b476c4528c5768370

What do you thinkg ?

**Comment by eugeneavry** [comment]
Hello, Marcos!

I'm terribly sorry for this delay.

> Using invariant culture will generate a breaking change :(

Right, I understand your concern. Thus, going with constructor overloads accepting particular culture is the best solution (exactly like you did). The main point here is to let your API consumers know about the possibility to specify culture by clearly stating it in the documentation.

> Instead of using null now uses the Culture provided, also the ToString methods uses the culture
99c1aec#diff-07405c1417977c1b476c4528c5768370

I have looked through the changes you had made, everything seems to be all right now.

**Comment by MarcosMeli** [comment]
No problem about the delay :+1: 

Thanks a ton for the report !!

**Pull request closed without merging**
