### PR TITLE
Implementation of include headers column name on DataTableToCsv

### PR DESCRIPTION
**Pull request by denistorresan**
Hello,
I implemented the ability to save CSV from DataTable with columns name as the first header row.

Hope this featues can be included into dev.

I added one method:

CsvEngine.DataTableToCsv(DataTable dt, string filename, bool includeHeaders, CsvOptions options);

if includeHeaders==true, than the DataTable column name is included.
Also there's the previous version of that method without the new parameter:

CsvEngine.DataTableToCsv(DataTable dt, string filename, CsvOptions options);

thank you!

### CODE REVIEW

**Comment by MarcosMeli** [comment]
Excellent !!

What do you think about adding the property IncludeHeaders to the CsvOptions ?

So we can avoid to add more parameters and expand the current one ?

Thanks

**Comment by denistorresan** [comment]
Hello and thanks to reply to me...!
I simply add a parameter (maybe we can change the name), that add column names taken from DataTable at the very first line of exported CSV.

es:  
DataTable structure is:  (id | name | surname)
With this data:
1 | john | smith
2 | al | pacino

Previous output of CSV was:
"1","john","smith"
"2","al","pacino"

Than (with includeHeaders=true) CSV will be:
"id","name","surname"
"1","john","smith"
"2","al","pacino"

This also was a request some guys asks on stackoverflow:

http://stackoverflow.com/questions/24485228/how-do-i-write-csv-file-with-header-using-filehelpers

If you need that I change something, please ask me!

Best regards!
denis

**Comment by denistorresan** [comment]
Ok so, here my proposal:

1) on CsvOptions, I'll add property ExportHeaderColumns (or you prefer IncludeHeaderColumns ?), like:

options.ExportHeaderColumns = true;

2) Delete my DataTableToCsv method, and include to the previous one my code

Let me know if it's ok for you I'll do the changes tomorrow!

**Comment by denistorresan** [comment]
Hello @MarcosMeli! I changed the code and now I'll pull a new request! 
Let me know if now it's ok.

Sample code:

//save in file system
CsvOptions options = new CsvOptions("Tempo1", ',', myDataTable.Columns.Count);
options.IncludeHeaderNames = true;
CsvEngine.DataTableToCsv(myDataTable, "c:\report.csv", options);

**Comment by MarcosMeli** [comment]
Excellent !!!
I will merge it but I need that you add a little test to avoid regressions and to validate it works fine two ways, i.e. if you write the file from the datatable that with the same backwise

The HeaderLines = 1 ignore the first line but not make the datable to get the column names back

Can you validate it ?

PS: Sorry for the delay, too much work here :hammer:

**Comment by denistorresan** [comment]
Hello @MarcosMeli ,

as I understand, HeaderLines = 1 is ONLY for read CSV into DataTable, and not for Writing it to a CSV file.
This option is not used inside DataTableToCsv method.

I think that all works good, because DataTableToCsv can write with headers, and if you want to read from the same CSV, you need to set HeaderLines = 1.

Let me know If you need something else, I'll take care!

Thank you and Bye!
Denis

**Comment by MarcosMeli** [comment]
In fact I want that when you read it back your code and same options you get the same datatable back with the column names on it

A test like this:

    //save in file system
    CsvOptions options = new CsvOptions("Tempo1", ',', myDataTable.Columns.Count);
    options.IncludeHeaderNames = true;

    CsvEngine.DataTableToCsv(myDataTable, "c:\report.csv", options);
    var myDataTable2 = CsvEngine.CsvToDataTable("c:\report.csv", options);

And check that myDataTable has same column names

What do you think
Thanks !!

**Comment by denistorresan** [comment]
Ok, now this code works ONLY if you change it with:

```c#
//save in file system
CsvOptions options = new CsvOptions("Tempo1", ',', myDataTable.Columns.Count);
options.IncludeHeaderNames = true;
options.HeaderLines = 1;

CsvEngine.DataTableToCsv(myDataTable, "c:\report.csv", options);
var myDataTable2 = CsvEngine.CsvToDataTable("c:\report.csv", options);
```

What we can do is to doing something (but I don't know if it's possible), that when you set:
```c#
options.IncludeHeaderNames = true;
```

automatically the code sets also:

```c#
options.HeaderLines = 1;
```
You think it's possible to do that? Using events or so on?

thanks!

**Comment by MarcosMeli** [comment]
That I was thinking

    public bool IncludeHeaderNames
    {
      get { return mIncludeHeaderNames; }
      set { 
                mIncludeHeaderNames = value; 
                if (value && HeaderLines == 0)
                     HeaderLines = 1
            }
     }

**Comment by denistorresan** [comment]
Ok, let me fix it! :)

**Comment by denistorresan** [comment]
Hello @MarcosMeli ! I added the fix you mentioned in the 174#issuecomment-157389933.
hope this works!

**Comment by denistorresan** [comment]
hello @MarcosMeli ! some feedback on my latest commit? bye! :)

**Comment by denistorresan** [comment]
Hello @MarcosMeli ! Some news about it?
I hope all is good and I can see the new version with also my feature... I need in my project! :D 

bye!

**Comment by denistorresan** [comment]
Hello @MarcosMeli ! Some news about it?
I hope all is good and I can see the new version with also my feature... I need in my project! :D

bye!

**Comment by killergege** [comment]
+1 I'm looking for this feature ! I need to export the headers with the data.
Is there a reason this pull request is still pending ?

**Comment by mcavigelli** [comment]
Hello there

I will look into this pull request, after I have finished working on #245.

Only looking at the surface, I do not see any tests.
Automated tests
1. make it much easier to understand the code
2. help to ensure the correctness of the change
3. allow fearless refactoring and maintenance of the FileHelpers library.

It would be nice to have tests for this change: anyone willing to add them?

Matthias

**Comment by mcavigelli** [comment]
With 01e6a2c the changes are in the master branch. Alpha NuGet Packages are available and contain the latest changes https://ci.appveyor.com/nuget/filehelpers.

I could not download the patch or merge the branch. I had to type it down from the webinterface.
It seems that the pull request did not feature any tests and therefore was not added to the master.

**Pull request closed without merging**
