### PR TITLE
Fixed building + testing on Mono

### PR DESCRIPTION
**Pull request by akoeplinger**
This is a collection of fixes that allow building and running the unit tests on Mono.
There are a small number of unit tests that fail on Mono, I moved them into the "NotOnMono" NUnit category and excluded them from Travis CI until they can be investigated. Should be better than not testing at all :)

### CODE REVIEW

**Comment by MarcosMeli** [comment]
Great !! Genious !!

I will merge that, anyway in the travis build maybe is better to only build the library and tests and not the Demos, WIzard and so on

The failing Test are mostly because the library defaults to Encondig.Default that works well on windows but in Mono it fail

Welcome :+1:

**Comment by akoeplinger** [comment]
Looks like I missed one other commit that makes the Travis tests pass, will open a follow-up commit :)

**Comment by MarcosMeli** [comment]
I just added a solution with the library and tests to avoid compile the rest of the projects:
https://github.com/MarcosMeli/FileHelpers/blob/master/FileHelpers.OnlyMainLibAndTests.sln

**Comment by akoeplinger** [comment]
I actually prefer building and testing the full .sln on CI, in my experience nobody pays attention until the build breaks :)

**Comment by MarcosMeli** [comment]
I agree, but, the rest of projects: Excel Interop, NPOI, Examples succeed in your builds ?
I left only main lib to speed up travis build time

**Comment by akoeplinger** [comment]
Yep, they built fine. I don't think you'll save more than a few seconds by excluding them, compilation is very fast.

**Comment by MarcosMeli** [comment]
You are right, just changed to FileHelpers.sln, all green:

https://travis-ci.org/MarcosMeli/FileHelpers/builds/72397991

Thanks

**Pull request merged**
